# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
import csv
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import *

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        uic.loadUi("MainWindow.ui", self)
        self.show()

        self.openButton.clicked.connect(self.openFileDialog)
        self.exitButton.clicked.connect(self.close)

        self.model = QtGui.QStandardItemModel(0,0)
        self.filter_proxy_model = QtCore.QSortFilterProxyModel()
        
    def openFileDialog(self):
        fn = QFileDialog.getOpenFileName()
        split_fn = os.path.splitext(fn[0])

        file_name = split_fn[0]
        file_extension = split_fn[1]

        if fn:
            if file_extension == ".csv":
                with open(file_name + file_extension, newline='') as f:
                    reader = csv.reader(f)
                    data = list(reader)
                    data_header = list(data[0])
                    data.pop(0)
                    
                    self.model = QtGui.QStandardItemModel(len(data) - 1, len(data[0]))
                    self.model.setHorizontalHeaderLabels(data_header)
                    self.filter_proxy_model.setSourceModel(self.model)

                    self.tableView.setModel(self.filter_proxy_model)
        
                    self.fillTable(data)

    def fillTable(self, data):
        for x in range(0, len(data)):
            for y in range(0, len(data[x])):
                item = QtGui.QStandardItem(data[x][y])
                self.model.setItem(x, y, item)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = MainWindow()
    sys.exit(app.exec_())
